### ISSUE TITLE
Feature suggest: Timetable support

### ISSUE THREAD

**Issue by Computerkrack** [Dlurak/dloolFrontend#14]
A simple timetable, that doesn't has to be visible (privacy, so it wouldn't be like the homework which are visible to everyone without account) but can help you choose the right expiration date when creating homework.
Maybe it could be implemented also just personally (e.g. the coloring of subjects) in the settings.

**Comment by Dlurak** [comment]
Good idea!  
Yes I think I will implement it similiar to the colors for subjects.  

As for the experation date it would be enough to store which subjects are on which weekday. So something like that:   

```json
{
	"monday": ["English", "Biology", "Hacking"],
	"tuesday": ["German", "Maths", "42"],
	"wednesday": ["Geography", "English"],
	"day": ["some", "other", "stuff"]
}
```

Currently the experation date gets autofilled to one week, this way Dlool could estimate when the next lesson will be and autofill the date to that date.

**Comment by Dlurak** [comment]
Safari has a different date picker then all other browsers. It's UI doesn't yet update but I'm already working on fixing that and am confident that I can close that issue for the last time very soon

**Comment by Computerkrack** [comment]
Bug:
You can't change the date, that is automatically put in from the timetable

**Comment by Dlurak** [comment]
With the new custom datepicker this issue can now be closed :)
