### ISSUE TITLE
Expiration Date not changable

### ISSUE THREAD

**Issue by Computerkrack** [Dlurak/dloolFrontend#17]
On my iPad (PWA) I can't change the date, when creating the homework.
The Calendar pop-up appears, but when a date is selected and I press OK the date (standardly one week ore based on timetable) does not change.

**Comment by Dlurak** [comment]
Safari lacks a js-api. 
I will need to either implement a custom date picker or find a good library. I guess I will choose shadcdn.

**Comment by Dlurak** [comment]
[This](https://www.shadcn-svelte.com/docs/components/date-picker) seems promising, I guess I will use it.

**Comment by Dlurak** [comment]
So now I've finally implemented a custom date picker which is the same across all browsers. The can be set manually again and the timetable also still works :)
