### ISSUE TITLE
Localization settings in the launcher

### ISSUE THREAD

**Issue by Dlurak** [Dlurak/dloolFrontend#18]
Currently the localization settings are only changeable in the settings [here](https://dlool.me/settings/local).
It would be nice if the country ideally also the state would be selectable in the launcher. Kinda like when using the launcher to change the theme.

**Comment by pdeep1506** [comment]
Can you please describe the issue furthermore ?

**Comment by pdeep1506** [comment]
I want to solve this issue

**Comment by Dlurak** [comment]
Of course :)

So on [Dlool](https://dlool.me) you can press `ctrl` + `k` or `cmd` + `k` on mac to open the "launcher".  
All entries of this launcher are defined in [this file](https://github.com/Dlurak/dloolFrontend/blob/Main/src/constants/launcher.ts).

---

When a user wants to change the localization settings (which are used for the newly added holiday feature) they need manually visit the sub site in the settings and choose an option from the select menus.  
But it would be a way better user experience if it would be possible to change the country/state directly from within the launcher. On Dlool you can try what I mean by pressing `ctrl` + `k` and then searching for *Theme*. You will be able to change the theme without visiting the settings, for countries/states it should work like this. You can take inspiration from [this](https://github.com/Dlurak/dloolFrontend/blob/Main/src/constants/launcher.ts#L213C2-L252C4) and [this](https://github.com/Dlurak/dloolFrontend/blob/Main/src/routes/settings/local/%2Bpage.svelte).

---

Just out of interest: How did you find my project? Did you hear my lightning talk?

**Comment by Dlurak** [comment]
I just assume you won't work on it anymore so I will do it myself soon
